### ISSUE TITLE
Question: is this project still maintened?

### ISSUE THREAD

**Issue by edbzn** [zeit/ng-deploy-now#10]
Hi, 

I'm wondering if this project is still the recommended way to deploy Angular apps using Now? Some dependencies seem to be outdated including the `now-client` and Angular related packages.

My problem is that I get an error when running `ng run my-app:deploy`.

```
An unhandled exception occurred: Cannot find module 'my-app/node_modules/@zeit/ng-deploy/node_modules/now-client/dist/src/index.js'. 

Please verify that the package.json has a valid "main" entry
```

The error comes from **`src/`** directory in `node_modules/now-client/dist/src/index.js` which doesn't exist.

I would be happy to contribute if this project is still valuable.

**Comment by jagansahu** [comment]
did you find a solution for this error, i'm running into the same problem

**Comment by edbzn** [comment]
Not really.
